### ISSUE TITLE
False positive for screen lock on Mac Mojave 10.14.4

### ISSUE THREAD

**Issue by smarbin** [Netflix-Skunkworks/stethoscope-app#135]
* **I'm submitting a ...**
  - [x] bug report
  
* **What is the current behavior?**
On Mac Mojave 10.14.4 with Stethoscope v3.0.4 I'm getting a green check mark and it says "Screen Lock is enabled" even though it is not enabled in the system control panel. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Choose System Preferences from the Apple menu.
2. Click Security or Security & Privacy.
3. Select the General tab.
4. Unlock the pane by clicking the lock in the lower-left corner and enter the administrator username and password.
5. UnCheck the "Require password" box.
6. Click "Rescan" on Stethoscope

* **What is the expected behavior?**

It should show a red X, and say "Screen Lock is disabled"

* **What is the motivation / use case for changing the behavior?**

Users might be tricked into believing their system is secure when it's not. 

* **Please tell us about your environment:**

  - Stethoscope Version: v3.0.4
  - Platform:
    - [x] Mac Mojave 10.14.4

  - Browser: [x] Chrome Version 73.0.3683.103 (Official Build) (64-bit)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

I will also submit two other related bugs, showing the same problem related to "automatic updates" and "screen lock when the system is idle."

Screenshot showing the screen lock bug: 
![Screen Lock OFF BUG](https://user-images.githubusercontent.com/20249846/56084918-9fbc5e80-5def-11e9-8e3c-b7f08ebf3401.png)

Screenshot showing the firewall status is working as intended: 
![Firewall off - Working as intended](https://user-images.githubusercontent.com/20249846/56084919-9fbc5e80-5def-11e9-8d01-f8cb4b541809.png)

**Comment by rmcvey** [comment]
Hi @smarbin, thanks for filing these issues! We are aware of this particular issue, and I agree that it is not handled optimally currently. Unfortunately it is no longer possible (as of macOS 10.13) to determine whether the user has screenlock enabled. This check is still valid for users of 10.12 or below, but since we can't make the determination, we show it is ok.

Our team has discussed this multiple times, but we can and should do better than this. I think the best approach for this would be to:
- Add version-based conditions in the instructions file so that we can provide specific directions for users where we can't determine the setting
- Have a separated set of suggestions / instructions that say "we can't show this as passing or failing, but you should make sure your computer requires a password to unlock"

I'll bring this back to the team.
