### ISSUE TITLE
Please provide AppImage for download on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [Netflix-Skunkworks/stethoscope-app#27]
https://github.com/Netflix-Skunkworks/stethoscope-app/blob/5d697e964105bf1a5bddccec4fb1d52eaa7e8b58/package.json#L52

Please provide the AppImage for download on GitHub Releases, then we can add it to the AppImageHub central directory of available AppImages. Thank you very much!

**Comment by rmcvey** [comment]
Hi @probonopd, thanks for opening our first issue! 🍾 

The app currently launches and runs on Linux, however there is a fairly large issue that we haven't had sufficient time to address: `osqueryi` seems to require elevated permissions on Linux to run many of our security checks (e.g. disk encryption status). Since only a tiny portion of the fleet we are supporting is Linux, we decided to prioritize full support for Windows and Mac platforms in our first release. We haven't set our goals for the next quarter, but I will bring up working on Linux support. 

In the meantime, we are open to suggestions and PRs.

**Comment by rmcvey** [comment]
We are still working on Linux support, and though I believe we are closer - we are not going to be publishing downloadable builds for any platform in the foreseeable future (at least until we determine our external distribution model).
